# Generated by Django 5.0.4 on 2024-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blackips',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blackips',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='blackips',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
