# Generated by Django 5.0.4 on 2024-04-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocklist', '0002_blackips_request_count_alter_blackips_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blackips',
            old_name='is_active',
            new_name='blocked',
        ),
    ]
